FROM resin/intel-nuc-debian

# Enable systemd init system in container
ENV INITSYSTEM on

RUN apt-get -q update && apt-get install -yq --no-install-recommends \
  build-essential \
  cmake \
  && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY . /usr/src/app
WORKDIR /usr/src/app

RUN ./install_opencv.sh
RUN ./build.sh
# RUN g++ -o hello hello.cpp

CMD ./run.sh
